### ISSUE TITLE
Crear carpeta layouts y los archivos footer, header

### ISSUE THREAD

**Issue by Matia5Ortega** [Matia5Ortega/Repo_TP2_Grupo7#22]
la dirección de carpeta debe quedar de la siguiente manera src/main/resource/templates/layouts

los archivos a crear dentro de la carpeta layouts son footer.html y header.html

sacar la estructura que tenían en el archivo index.html

**Comment by Lucas-Soto** [comment]
Creacion de la carpeta layouts en la carpeta template como asi tambien los archivos footer.html para el pie de pagina y el archivo header.html para el encabezado del archivo Index.html.
