### ISSUE TITLE
Crear las entidades Sucursal y una para Consejos de salud que se usarán en el proyecto

### ISSUE THREAD

**Issue by Matia5Ortega** [Matia5Ortega/Repo_TP2_Grupo7#28]
Dentro del paquete model crear todas las clases java que representen las entidades: Sucursal y una para Consejos de salud

Cada entidad debe tener sus atributos.
Agregue en la declaración de la clase los métodos accesores (getters y setters).
Un constructor parametrizado.

**Comment by Lucas-Soto** [comment]
Se creo la identidad para Sucursal y Consejo de salud, cada uno con sus constructores parametrizados, como asi tambien los getters y setters.
