### ISSUE TITLE
Incorporar el uso de Bootstrap en el proyecto en desarrollo.

### ISSUE THREAD

**Issue by dariofunes** [Matia5Ortega/Repo_TP2_Grupo7#35]
Incorporar el uso de Bootstrap en el proyecto en desarrollo. A las paginas productos.html, index.html y nueva_sucursal.html
Considerar el uso de las clases bootstrap para organizar todo el contenido de los archivos html:
Containers
Filas
Columnas
Alineación
Formularios y componentes que considere necesario en las páginas del proyecto.
El sitio se debe adaptar (ser responsive) para los diferentes tamaños de dispositivos

Agregar la documentación interna del código.

**Comment by Lucas-Soto** [comment]
Se modifico el archivo Index.html aplicando las clases del  bootstrap a los elementos para organizar el contenido en contenedores, filas y columnas. Además, he utilizado la clase img-fluid para hacer que la imagen sea responsive.
